(define toolbar-display-time 'mode)
(define toolbar-show-action-based-switcher-button? #t)
(define imsw-coverage 'system-global)
(define toolbar-show-switcher-button? #f)
(define toolbar-show-pref-button? #t)
(define toolbar-show-dict-button? #f)
(define toolbar-show-input-pad-button? #f)
(define toolbar-show-handwriting-input-pad-button? #f)
(define toolbar-show-help-button? #f)
(define toolbar-help-browser 'system)
(define toolbar-help-browser-name "firefox")
(define toolbar-icon-for-dark-background? #f)
(define mozc-widgets '(widget_mozc_input_mode widget_mozc_kana_input_method widget_mozc_tool))
(define default-widget_mozc_input_mode 'action_mozc_direct)
(define mozc-input-mode-actions '(action_mozc_direct action_mozc_hiragana action_mozc_katakana action_mozc_halfkana action_mozc_halfwidth_alnum action_mozc_fullwidth_alnum))
(define default-widget_mozc_kana_input_method 'action_mozc_roma)
(define mozc-kana-input-method-actions '(action_mozc_roma action_mozc_kana))
